version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: "0 * * * *"
    groups:
      npm-minor-patch:
        update-types: [minor, patch]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: "0 * * * *"
    groups:
      actions:
        update-types: [major, minor, patch]
